CREATE TABLE "GCG_5883_COLUMNS" (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "ORDER_SORT" NUMERIC(4,0),
 "TOOL" CHAR(4),
 "GAGE" CHAR(4),
 "NOTES" CHAR(100),
 "QA" CHAR(10),
 "PALLET" CHAR(30),
 "PROGRAM" CHAR(30),
 "ACYT" CHAR(30),
 "SETUP_NOTE" CHAR(30),
 "RUNTIME_NOTE" CHAR(30),
PRIMARY KEY(ID));

